name: Swift

on:
  push:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_spm_mac:
    runs-on: macos-arm
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
